---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(yaml)
library(data.table)
```

```{r listing-reading}
fns <- list.files("../data", full.names = TRUE) |> sort()
fns <- fns[!grepl("README[.]md$", fns)]
  
headers <- lapply(fns, \(f) {
  f <- readLines(f)
  ids <- which(grepl("^---\\s*$", f))[1:2]
  yaml::read_yaml(text = paste(f[ids[1]:ids[2]], collapse = "\n"))
  })
```

# General table

```{r create-tables}
#' Takes a null value and returns `""`
null2empty <- function(x) {
  if (length(x))
    x
  else
    ""
}

# Creates a github type link
linker <- function(f) {
  f <- gsub("[,.:;]+", "", f)
  f <- gsub("[^a-zA-Z0-9]+", "-", f) |> tolower()
  sprintf("([link](#%s))", f)
}

tab <- lapply(headers, \(f) {
  
  title    <- f$`title-paper`
  software <- f$`software-package`
  doi      <- f$doi
  
  # Processing software tools
  software <- if (length(software)) {
    sprintf(
      "[%s (%s)](%s)",
      sapply(software, "[[", 2),
      sapply(software, "[[", 1),
      sapply(software, "[[", 3)
    ) |> paste(collapse = ", ")
  } else
    ""
  
  # Processing DOI
  doi <- if (length(doi)) {
    sprintf("[%s](https://doi.org/%s)", doi, doi)
  } else 
    ""
  
  # Processing keywords
  keywords <- f$keywords
  keywords <- if (length(keywords))
    paste0("`", keywords, "`", collapse = ", ")
  else
    ""
  
  # Putting all together
  data.table(
    title    = paste(
      null2empty(title),
      linker(title)
      ),
    software = software,
    doi      = null2empty(doi),
    keywords = keywords
  )
  
}) |> rbindlist(fill = TRUE)

tab[, keywords := tolower(keywords)]

tab |> knitr::kable(row.names = FALSE)
```

# Details

```{r printer, results='asis'}
for (i in seq_along(fns)) {
  
  cat("\n\n## ")
  cat(headers[[i]]$`title-paper`, "\n\n")
  cat("\n")
  
  # Processing the text
  f <- readLines(fns[i], warn = FALSE)
  
  ids <- which(grepl("^---\\s*$", f))[1:2]
  cat(f[-(ids[1]:ids[2])], sep = "\n")
  
  cat("\n([go back](#general-table))")
  cat(sprintf("([more](%s))", fns[i]))
}
```

