---
output: github_document
title: Full table
---

This repository compiles information about epidemics modeling. The goal is
to provide a centralized and standardized way of adding annotated data entries
about methods, software, data, and scientific articles on the subject. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(yaml)
library(data.table)
if (file.exists("functions.R")) {
  source("functions.R")
} else
  source("docs/functions.R")
```

```{r results='asis'}
menu_maker("")
```


```{r listing-reading, warning=FALSE}
fns <- list.files("../data", full.names = TRUE) |> sort()
fns <- fns[!grepl("README[.]md$", fns)]
headers <- get_headers(fns)
```

```{r create-tables}
tab <- lapply(headers, \(f) {
  
  title    <- f$`title-paper`
  software <- f$`software-package`
  doi      <- f$doi
  
  # Processing software tools
  software <- if (length(software)) {
    sprintf(
      "[%s (%s)](%s)",
      sapply(software, "[[", 2),
      sapply(software, "[[", 1),
      sapply(software, "[[", 3)
    ) |> paste(collapse = ", ")
  } else
    ""
  
  # Processing DOI
  doi <- if (length(doi)) {
    sprintf("[%s](https://doi.org/%s)", doi, doi)
  } else 
    ""
  
  # Processing keywords
  keywords <- f$keywords
  keywords <- if (length(keywords)) {
    keywords <- tolower(keywords)
    linker(keywords, paste0("**`", keywords, "`**"), "by-keyword.md") |>
      paste(collapse = ", ")
  } else
    ""
  
  # Putting all together
  data.table(
    title    = null2empty(title),
    software = software,
    doi      = null2empty(doi),
    keywords = keywords
  )
  
}) |> rbindlist(fill = TRUE)

# Adding a link
tab[, title := sprintf(
  "%s (**[link](entries/%s)**)",
  title,
  gsub("../data/", "", names(headers))
  )]

tab[, keywords := tolower(keywords)]

tab |> knitr::kable(row.names = FALSE)
```

```{r echo = FALSE}
json <- '{"schemaVersion": "1", "label": "Entries", "message": "%i", "color": "green"}'
cat(sprintf(json, nrow(tab)), file = "info/entries.json")
```



