# Controls when the workflow will run
#
name: Build md
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: Ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      cntr: gvegayon/wepidemics:latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${cntr}

      - name: Compile
        run: |
          cd docs
          docker run -i --rm -v$(pwd)/../:/home/ -w/home/docs ${cntr} make -B

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add docs/*md
          git add docs/entries/*md 
          git commit -a -m 'Re-build markdown files' || echo Nothing has changed
          git push origin || echo "No changes to commit"
